# Delete a WordPress site

- assert:
    that:
      - inventory_hostname in wp_destructive
      - wp_destructive[inventory_hostname] == 'wipe'
  register: _sanitycheck_delete
- meta: end_play
  when: _sanitycheck_delete.failed

- include_vars: jahia2wp-vars.yml

- name: jahia2wp.py clean
  shell: "{{ jahia2wp_shell }} clean {{ wp_env }} {{ jahia2wp_url }}"
  environment: "{{ jahia2wp_env }}"
  when: wp_destructive[inventory_hostname] == 'wipe'
