# Generate a WordPress site, without paying too much attention to the
# exact DB configuration, lineup of plugins etc. (Typically because
# we are going to restore these from a database dump)

# Create empty plugin hierarchy
- name: Empty plugins hierarchy for jahia2wp generate "quick"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_remote_tmp }}/no-plugins/generic"
    - "{{ ansible_remote_tmp }}/no-plugins/specific"
  changed_when: false
- name: Empty config-lot1.yml for jahia2wp generate "quick"
  copy:
    dest: "{{ ansible_remote_tmp }}/no-plugins/generic/config-lot1.yml"
    content: |
      plugins: []
  changed_when: false

- name: jahia2wp.py generate "quick"
  shell: "export PLUGINS_CONFIG_BASE_PATH={{ ansible_remote_tmp }}/no-plugins; {{ jahia2wp_shell }} generate {{ wp_env }} {{ jahia2wp_url }}"
  environment: "{{ jahia2wp_env }}"
  when: wp_restore_from != 'generate'
