# Undump the contents from local WXR (XML) files
#
# Expected directory layout in {{ undump_local_dir }}:
#
#    foo1.xml
#    foo2.xml
#
# All .xml files uder {{ undump_local_dir }} will be undumped into
# this Wordpress, in no particular order.

- assert:
    that:
      - inventory_hostname in wp_destructive
      - wp_destructive[inventory_hostname] is search("^(data|wipe)")
    msg: |
      Please specify a write permission for {{ inventory_hostname }} using the 'wp_destructive' command line parameter. See examples in src/ventilation/Makefile or ansible/roles/wordpress/defaults/main.yml .

- include_vars: jahia2wp-vars.yml  # For jahia2wp_dir, used by dump-vars below
- include_vars: dump-vars.yml

- name: List plugins
  command: "{{ wp_cli_command }} plugin list"
  register: wp_plugin_list
  changed_when: false

- name: Install wordpress-importer
  command: "{{ wp_cli_command }} plugin install --activate wordpress-importer"
  when: "'wp-importer' not in wp_plugin_list.stdout"

- copy:
    src: "{{ item }}"
    dest: "{{ undump_remote_tmpdir }}"
  with_fileglob:
    - "{{ undump_local_dir }}/*.xml"

- name: "Create {{ undump_remote_tmpdir }}"
  file:
    state: directory
    path: "{{ undump_remote_tmpdir }}"
    recurse: yes

- name: Copy importer.php
  copy:
    src: "{{ playbook_dir }}/../../src/importer.php"
    dest: "{{ undump_php_script }}"

- name: "Undump from {{ undump_remote_tmpdir }}/*.xml"
  shell: "set -e -x ; cd '{{ undump_remote_tmpdir }}'; for file in *.xml; do {{ wp_cli_command }} --require={{ undump_php_script }} jahia2wp import -fetch-attachments $file; done"
  register: undump_php_results

- debug:
    var: undump_php_results
