# file: roles/wordpress/vars/main.yml
#
# Define variables that are used throughout this role.
#
# See ../defaults/main.yml for the variables the user is expected to
# provide (either through the inventory file, so-called "group_vars",
# or on the command line)
#
# See also the other files in this directory for variables that are
# only used by some of the tasks in this role. While this file,
# roles/wordpress/vars/main.yml is implicitly imported whenever the
# "wordpress" role is in play in a playbook, the other files in this
# directory need to be imported explicitly using the import_vars
# task.

# The top-level directory of this WordPress instance
wp_dir: "/srv/{{ wp_env }}/{{ wp_hostname }}/htdocs/{{ wp_path }}"

# The .htaccess commanding over this WordPress instance
wp_htaccess_path: "{{ wp_dir }}/.htaccess"

# The path to the wp-config.php file
wp_path_config_php: "{{ wp_dir }}/wp-config.php"

# The prefix to invoke the WP-CLI for this WordPress instance
wp_cli_command: "wp --path={{ wp_dir }}"

# The public-facing URL of this instance
wp_base_url: "https://{{ wp_hostname }}/{{ wp_path }}"

wp_themes_dir:  "{{ wp_dir }}/wp-content/themes"
wp_plugins_dir: "{{ wp_dir }}/wp-content/plugins"
